import {  getCourseByIdWithPublishedChaptersAndUserProgress } from "@/actions/courses";
import { getProgress } from "@/actions/user-progress";
import CourseNavbar from "@/components/course/course-navbar";
import CourseSidebar from "@/components/course/course-sidebar";
import { auth } from "@clerk/nextjs";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import toast from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function CourseLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { courseId: string;}
}>) {
    const { userId } = auth();
    if (!userId) {
        toast.error("Unauthorized!");
        return redirect("/");
    }
    const course = await getCourseByIdWithPublishedChaptersAndUserProgress(userId,params.courseId);

    const progressCount = await getProgress(userId,course.id);

  return (
    <div className="h-full ">
        <div className="h-[80px] md:pl-80 fixed inset-y-0 w-full z-50">
            <CourseNavbar course={course} progressCount={progressCount} />
        </div>
        <div className="hidden md:flex h-full w-80 flex-col fixed inset-y-0 z-50">
            <CourseSidebar course={course} progressCount={progressCount} />
        </div>
      <main className="md:pl-80 pt-[80px] h-full">
      {
        children
      }
      </main>
    </div>
  );
}
